### ISSUE TITLE
The binary operator LessThan is not defined for the types 'System.String' and 'System.String'.

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#253]
In CRM it is possible to use the 'less than' operator in a fetchXML statement on an attribute of type string to get records where the string is before the search expression in the alphabet.

So in a real CRM environment, this query:
`<fetch mapping='logical'>
    <entity name='bsp_college'>
    <attribute name='bsp_name'/>
    <filter type='and'>
        <condition attribute='bsp_name' operator='lt'  value='C' />
    </filter>
    </entity>
</fetch>`

works fine and returns four entities in my dev environment which begin with letters before C.

However, the same query fails when using FakeXrmEasy with this error:
_The binary operator LessThan is not defined for the types 'System.String' and 'System.String'._

I don't _think_ that this message is being explicitly riased by your code.

I suspect that this is actually because I'm not using proxyTypes for the test and it can't tell what the type of the attribute is, so _maybe_ the real solution to the problem is to add a more meaningful message like the one you use for arithmetic comparison: _"When using arithmetic values in Fetch a ProxyTypesAssembly must be used in order to know which types to cast values to."_

**Comment by bwmodular** [comment]
Hmm, actually I switched to using ProxyTypes and still get the same error, so maybe it's not that...

**Comment by jordimontana82** [comment]
Hi Ben,

Sorry for the delay on this, and thanks for spotting this issue. I believe the issue has to do with the way FakeXrmEasy translates fetchxml and queryexpressions into LINQ, by building an expression tree. For the 'lt' operator, it is simply translating it to a LessThan expression, and it looks like it is not supported. 

We could call CompareTo first, and then do the LessThan based on its result (-1, 0 or 1).

**Comment by bwmodular** [comment]
Cool - I'll take a look at fixing this next week...

**Comment by bwmodular** [comment]
OK, so I wrote a couple of failing tests for LT and GT and then took a look at TranslateConditionExpressionLessThan and have absolutely no idea what to do! I tried a few things but nothing really made sense so I'm going to have to either get another hint from you or get you to do it. Sorry! Not urgent BTW.

Here's the test which fails with the expected message:
````        [Fact]
        public void FetchXml_Operator_Lt_Execution_On_Strings()
        {
            var ctx = new XrmFakedContext();

            var fetchXml = @"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                              <entity name='contact'>
                                    <attribute name='nickname' />
                                        <filter type='and'>
                                            <condition attribute='nickname' operator='lt' value='B' />
                                        </filter>
                                  </entity>
                            </fetch>";

            var ct1 = new Contact() { Id = Guid.NewGuid(), NickName = "Al"};
            var ct2 = new Contact() { Id = Guid.NewGuid(), NickName = "Bob"};
            var ct3 = new Contact() { Id = Guid.NewGuid(), NickName  = "Charlie"};
            ctx.Initialize(new[] { ct1, ct2, ct3 });
            var service = ctx.GetFakedOrganizationService();

            var collection = service.RetrieveMultiple(new FetchExpression(fetchXml));

            Assert.Equal(1, collection.Entities.Count);
            Assert.Equal("Al", collection.Entities[0]["nickname"]);
        }
````

**Comment by jordimontana82** [comment]
Sorry for the delay Ben. Will look into this...

**Comment by jordimontana82** [comment]
Hi Ben, this is fixed in v1.37.3 now.

**Comment by bwmodular** [comment]
Thanks Jordi, I can see the commits you've made to the repo and I've updated my project to use 1.37.3 but still get the same error.
To check against VS Caching, I created a new LinqPad script, imported 1.37.3 and still get the same error.

I've also downloaded the latest version of the project from GitHub and all of the tests run ok, including the ones in
FakeXrmEasy.Tests.FakeContextTests.TranslateQueryExpressionTests.OperatorTests.Strings

Could there be some NuGet cache issue or something? I assume if 1.37.3 is available on nuGet that it must be the righ version, but....
 
Here's the script:
````
var fakedContext = new XrmFakedContext();
var fakedService = fakedContext.GetOrganizationService();

Entity college = new Entity() { Id = Guid.NewGuid(), LogicalName = "bsp_college", 
Attributes = { {"bsp_name","Brasenose"}} }; 

fakedContext.Initialize(new List<Entity>() {college});

string FetchXml = @"<fetch mapping='logical'> 
<entity name='bsp_college'>
	<attribute name='bsp_name'/>
	<filter type='and'>
		<condition attribute='bsp_name' operator='lt' value='C' />
	</filter>
</entity>
</fetch>";

EntityCollection ec = fakedService. RetrieveMultiple(new FetchExpression(FetchXml));

foreach (var c in ec.Entities)
{
	c["bsp_name"].Dump();
}````

which fails with:

The binary operator LessThan is not defined for the types 'System.String' and 'System.String'.

**Comment by jordimontana82** [comment]
Hi Ben, if you try with early bound entities, do you get the same?  I added 4 different scenarios with Lt and Gt but it was using early bound entities only.

**Comment by bwmodular** [comment]
Fails with both early and late bound entities. 2 tests below both fail. It seems to work fine for Query Expressions, but not for FetchXML.
```
        [Fact]
        public void Test_Fetch_Less_Than_Operator_With_String_Late_Bound()
        {
            var fakedContext = new XrmFakedContext();
            var fakedService = fakedContext.GetOrganizationService();

            Entity college = new Entity()
            {
                Id = Guid.NewGuid(),
                LogicalName = "bsp_college",
                Attributes = { { "bsp_name", "Brasenose" } }
            };

            fakedContext.Initialize(new List<Entity>() { college });

            string FetchXml = @"<fetch mapping='logical'> 
<entity name='bsp_college'>
	<attribute name='bsp_name'/>
	<filter type='and'>
		<condition attribute='bsp_name' operator='lt' value='C' />
	</filter>
</entity>
</fetch>";

            EntityCollection ec = fakedService.RetrieveMultiple(new FetchExpression(FetchXml));

            Assert.Equal(ec.Entities.Count,1);
        }

        [Fact]
        public void Test_Fetch_Less_Than_Operator_With_String_Early_Bound()
        {
            var fakedContext = new XrmFakedContext() {ProxyTypesAssembly = Assembly.GetAssembly(typeof(Account))};
            var fakedService = fakedContext.GetOrganizationService();

            Entity account = new Account() {Name = "Bob"};

            fakedContext.Initialize(new List<Entity>() { account });

            string FetchXml = @"<fetch mapping='logical'> 
<entity name='account'>
	<attribute name='name'/>
	<filter type='and'>
		<condition attribute='name' operator='lt' value='C' />
	</filter>
</entity>
</fetch>";

            EntityCollection ec = fakedService.RetrieveMultiple(new FetchExpression(FetchXml));

            Assert.Equal(ec.Entities.Count, 1);
        }
```

**Comment by jordimontana82** [comment]
Weird, fetchxml is translated into query expressions and in turn into LINQ, so they should behave the same.

Will take a look later on today

**Comment by jordimontana82** [comment]
Hi Ben,

Added more tests for fetchXml and it was indeed working fine for early bound entities. It wasn´t working for dynamic entities though but that has been fixed in the latest commit.

I think in your second test you are [missing the Id = Guid.NewGuid() bit](https://github.com/jordimontana82/fake-xrm-easy/blob/master/FakeXrmEasy.Tests.Shared/Issues/Issue253.cs#L52), that's why it's failing. Could you try again pls?

I'll push another version of the package which has support for dynamic entities. But it is much better to use early bound than late bound. With early bound type checking is precis as it uses the declared type. With late bound, however, is just "guessing" types based on actual values on the right hand side of the expression, which is not that ideal.

**Comment by bwmodular** [comment]
Sorry - my bad for not spotting the error on the early bound. Working for both early and late now.
Agreed about early vs late bound entities. At the moment I'm retrofitting tests into old projects which are using latebound classes, but on the whole we are using early bound.
Thanks for sorting this....

**Comment by jordimontana82** [comment]
No worries, glad is working now : )

**Comment by fallasd** [comment]
I am trying to retro-fit xUnit tests to some legacy code. I am using FakeXrmEasy.9. IOrganisationService.Retrieve(..) works fine, but not IOrganisationService.RetrieveMultiple(..). The latter throws the exception mentioned in the above thread ('When using arithmetic values in Fetch a ProxyTypesAssembly must be used in order to know which types to cast values to').

I can see in the Extensions code that it is testing for IsNumeric which has been set to true (refer to the FetchXml construction in the example). As this is legacy code, I am in my ability to convert the 'anonymous' Entity instance to a class.

The failing unit test follows (apologies if it is a bit long):

        public void ThrowsUseArithmeticExceptionMessage()
        {
            string _productId = "CACE22F3-C53D-43C0-8622-A43250B937E9";

            Entity _map = new Entity("sys_prodaffiliateunitmap")
            {
                Id = Guid.NewGuid()
            };

            _map.Attributes["sys_prodaffiliateunitmapid"] = Guid.NewGuid();
            _map.Attributes["sys_name"] = "sys_prodaffiliateunitmap";
            _map.Attributes["sys_uom"] = new EntityReference("sys_uom", Guid.NewGuid());
            _map.Attributes["sys_isdefaultunit"] = 2;
            _map.Attributes["sys_affiliate"] = 1;
            _map.Attributes["sys_product"] = Guid.Parse(_productId);

            string _fetchProductAffiliateUnit =
               @"<fetch version='1.0' output-format='xml-platform' mapping='logical' distinct='false'>
                <entity name='sys_prodaffiliateunitmap'>
                    <attribute name='sys_prodaffiliateunitmapid'/>
                    <attribute name='sys_name'/>
                    <attribute name='sys_uom' />
                    <attribute name='sys_isdefaultunit'/>
                    <filter type='and'>
                        <condition attribute='sys_product' operator='eq' value='{1}'/>
                        <condition attribute='sys_affiliate' operator='eq' value='{0}'/>
                    </filter>
                </entity>
            </fetch>";

            FetchExpression _fetchExpression = new FetchExpression(string.Format(_fetchProductAffiliateUnit,
                                                                                 1,
                                                                                 "CACE22F3-C53D-43C0-8622-A43250B937E9"));

            XrmFakedContext _context = new XrmFakedContext();
            _context.Initialize(new List<Entity>() { _map });
            IOrganizationService _service = _context.GetFakedOrganizationService();

            EntityCollection _collection = _service.RetrieveMultiple(_fetchExpression);

            Assert.Equal(1, _collection.Entities.Count);
        }
