### ISSUE TITLE
This / Next / Last Week Condition Operator Tests failing

### ISSUE THREAD

**Issue by bwmodular** [jordimontana82/fake-xrm-easy#543]
**Describe the bug**
The Condition Operator Tests for This/Next/Last week are failing, even though I've not changed anything since last running all of the tests in the solution.

I will take a look and try and work out why, but has anyone else experienced this?

**To Reproduce**
Open the Solution, run all tests. 18 of them fail - see screenshot below.

** FakeXrmEasy and Dynamics 365 / CRM version **
All versions - in the FakeXrmEasy solution itself

**Screenshots**
![image](https://user-images.githubusercontent.com/1889586/104600698-4131ad80-5671-11eb-9093-48ea1e6bf6f0.png)

**Comment by jordimontana82** [comment]
Thanks Ben, I've found out this wasn't working as expected when migrating to v2 so I fixed it there, it was calculating more than 7 days really...  

The code is substantially different in the way is structured between the 2 versions so I'll post it here if you want to try in your own fork?

I've changed it to this in v2:

    case ConditionOperator.ThisWeek:
       fromDate = today.ToFirstDayOfWeek();
       toDate = fromDate?.AddDays(6);
       break;
    case ConditionOperator.LastWeek:
       fromDate = today.AddDays(-7).ToFirstDayOfWeek();
       toDate = fromDate?.AddDays(6);
       break;
    case ConditionOperator.NextWeek:
       fromDate = today.AddDays(7).ToFirstDayOfWeek();
       toDate = fromDate?.AddDays(6);
       break;

With this new DateTime extension:

    public static DateTime ToFirstDayOfWeek(this DateTime dateTime)
    { 
        var dayOfWeekDelta = (int)dateTime.DayOfWeek - (int)CultureInfo.CurrentCulture.DateTimeFormat.FirstDayOfWeek;
        var delta = (7 - dayOfWeekDelta) % 7;
        return dateTime.AddDays(- delta);
    }

**Comment by bwmodular** [comment]
Thanks Jordi - I'll have a go at implementing in my own v1 fork and let you know,,,

**Comment by bwmodular** [comment]
Hi Jordi,
I added your datetime extension and re-implemented the ConditionOperaters as you have in v2, but notice that the same tests are still failing randomly. If I run one of the tests 10 times in a row, they fail about half of the time - I suspect something to do with the getRandomDateOfWeek function.
So... I started to rewrite the tests themselves, but then noticed something about the ToFirstDayOfWeek method you've posted.
I'm writing this on Saturday and it's telling me that the first day of this week is last Thursday.
Here's a little LINQPad script I wrote to test:
![image](https://user-images.githubusercontent.com/1889586/104819006-bf818180-5822-11eb-8440-aecbbe895515.png)
Am I misunderstanding something, or is the method not working as you'd expect? Unless Brexit has brought about some strange alterations to our calendars I'd expect the First day of the week to be Sunday, or Monday, but definitely not Thursday! Are the tests working OK in v2?

**Comment by bwmodular** [comment]
This seems to work. I'll use it in my local instance and see if I can get the tests working again:
![image](https://user-images.githubusercontent.com/1889586/105517289-c6027400-5cce-11eb-96aa-99e6b3707e3f.png)

**Comment by jordimontana82** [comment]
Sorry for the delay Ben, I'll revisit this in v2 and will get back to you.

**Comment by bwmodular** [comment]
I have something working in v1 - I'll do a PR in the next couple of days and you can take a look.
